[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "panda3d-egg-syntax-bible"
authors = [{name = "loonatic", email = "its@loony.pw"}]
dynamic = ["0.1", "Unofficial readthedocs page for Panda3D EGG syntax"]
