[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "panda3d-egg-bible"
authors = [{name = "loonatic", email = "its@loony.pw"}]
dynamic = ["0.1", "Unofficial knowledge base revolving around the Panda3D EGG file format"]
